(use-package lsp-mode :ensure t :commands lsp)
(use-package lsp-ui :ensure t :commands lsp-ui-mode)
(use-package company-lsp :ensure t :commands company-lsp)
(use-package lsp-haskell :ensure t)
(add-hook 'haskell-mode-hook #'lsp)
