(use-package virtualenvwrapper :ensure t
  :init
  (setq venv-location "~/.virtualenvs")
  )

(use-package jedi :ensure t)
(use-package py-isort :ensure py-isort)
(add-hook 'python-mode-hook
          (lambda()
            (hack-local-variables)
            (when (boundp 'project-venv-name)
              (venv-workon project-venv-name))
            (visual-line-mode t)
            (hs-minor-mode t)
            (adaptive-wrap-prefix-mode t)
            (local-set-key (kbd "\e\en") 'flycheck-next-error)
            (local-set-key (kbd "C-c C-f") 'py-isort-buffer)
            (local-set-key (kbd "C-c t") 'nosetests-one)
            (setq jedi:complete-on-dot t)
            (setq jedi:setup-keys t)
            (setq jedi:tooltip-method nil)

            (jedi:setup)
            (flycheck-mode t)
            (flycheck-disable-checker 'python-pycompile)
            ;; (flycheck-popup-tip-mode t)
            (setq outline-regexp "def\\|class ")
            (local-set-key (kbd "RET") 'newline-and-indent)
            )
          )
